### ISSUE TITLE
"Registrieren" (german) button text is not fitting in one line in Login/Register

### ISSUE THREAD

**Issue by andre-stefanov** [NexdApp/nexd-ios#105]
<img width="462" alt="Bildschirmfoto 2020-04-22 um 8 09 14 PM" src="https://user-images.githubusercontent.com/4808362/80017725-50fed580-84d5-11ea-8b30-7f1fe01803ec.png">

**Comment by schroepf** [comment]
Fixed with pr #121

**Comment by schroepf** [comment]
fixed
