### ISSUE TITLE
Update input validation to backend policy

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-ios#42]
Validation of the input form for user registration is based on old backend validation rules which are no longer valid.

The input validation for all text fields in user registration needs to be adapted to ne new validation rules of the backend:
- password length
- phone number format (backend uses libphonenumber for validation)

**Comment by fanick-ber** [comment]
good catch. Goes hand in hand with the validation and error catching that is missing in most places.

**Comment by fanick-ber** [comment]
I've merged a PR which should document all validations in the swagger. Can you use this? 
https://github.com/NexdApp/nexd-backend/pull/66

![image](https://user-images.githubusercontent.com/4163912/79055181-43cb2680-7c4b-11ea-9370-18c2c915d301.png)

**Comment by schroepf** [comment]
for phone number validation we could use:
- https://github.com/marmelroy/PhoneNumberKit
- https://github.com/iziz/libPhoneNumber-iOS

**Comment by schroepf** [comment]
That's the backend validation errors we should consider during offline validation:

RegistrationViewController:
- "email must be an email", (e.g.: a@b.com is valid, a@b.c is not valid)
- "password must be longer than or equal to 8 characters"

UserDetailsViewController:
- "phoneNumber must be a valid phone number"

RegistrationViewController:
- "phoneNumber must be a valid phone number"

Transcribe*:
- "phoneNumber must be a valid phone number"

**Comment by fanick-ber** [comment]
> * "email must be an email", (e.g.: [a@b.com](mailto:a@b.com) is valid, [a@b.c](mailto:a@b.c) is not valid)

If it's of any help, validation is done through this function: https://github.com/validatorjs/validator.js/blob/master/src/lib/isEmail.js
