### ISSUE TITLE
User not logged out on unauthorized backend requests

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-ios#57]
Issue occurred when switching from "prod" to "staging" backend:
- user was logged in on prod
- staging app was installed
- app tried to access backend with the "prod" account

Backend response for own profile was (but probably 401 should also be treated as unauthorized): 
```
Status: 404, error: unsuccessfulHTTPStatusCode, data: {
    path = "/api/v1/users/me";
    statusCode = 404;
    timestamp = "2020-04-12T18:08:22.469Z";
}
```

This is how the app looks in this case (just empty, no error message):
![Screen Shot 2020-04-12 at 20 16 15](https://user-images.githubusercontent.com/2974425/79076460-8ef04280-7cfa-11ea-9928-f278bded1d07.png)

**Comment by fanick-ber** [comment]
I think permission denied and unauthorized are currently not working well. I have an issue already open: https://github.com/NexdApp/nexd-backend/issues/68

**Comment by fanick-ber** [comment]
@schroepf I would probably tend to leave the errors as is. Can you confirm that switching the environment leads to a 401 and not a 404 status on this request?

**Comment by schroepf** [comment]
@fanick-ber No, I can't confirm that. Still the same "problem". A bearer token retrieved on one environment seems to work for all requests on the other environment. Except of course all requests which take a `me` as a parameter - they lead to 404 errors.

**Comment by schroepf** [comment]
I could also retest this with swagger ui..

**Comment by fanick-ber** [comment]
That is the correct behavior. 
For simplification reasons, both secrets are the same. 
But your user ids are not ;-)

We can have different secrets, you will get 401 erros then.

**Comment by schroepf** [comment]
alright... so I'll logout users if they either get 401 for any request or 404 for `GET /users/me`
