### ISSUE TITLE
App can be used without accepting the privacy policy

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-ios#69]
Steps to reproduce
- register new user
- on "user details" screen right after registration kill the app and restart
-> user can open the app without having accepted the privacy policy

**Comment by schroepf** [comment]
at the moment link to privacy policy doesn't work anymore

**Comment by schroepf** [comment]
seems the link has changed: https://www.nexd.app/privacy

**Comment by schroepf** [comment]
this is being worked on by christian at the moment

**Comment by ChristianSchmutte** [comment]
Resolved with #100
