### ISSUE TITLE
Helper workflow: Give possibility to "continue" working on old help lists

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-ios#74]
Currently every time the `HelperRequestOverviewViewController` is opened a nes HelpList instance will be created for the currently logged in user. All requests which were added to previous help lists would be lost and never worked on - thats potentially evil.

A fix could be to check for any pending help lists, if there are any show a modal list to the user to chose which one he wants to continue working on and use that selected list instead of creating a new one.

To fix this issue we should check the `GET /help-lists` API if there are still active help lists for the current user. If yes then reuse that existing list, and prefill the "Accepted lists" section with all the requests from the unfinished list. Otherwise use the already existing logic and just start a new help list.

<img width="180" alt="Bildschirmfoto 2020-04-22 um 22 42 59" src="https://user-images.githubusercontent.com/2974425/80031990-cd4fe380-84ea-11ea-885e-31542f298554.png">

**Comment by fanick-ber** [comment]
We had the idea to restrict the backend to only one active help list. That would prevent this, but we were not sure if it makes enough sense business wise?

**Comment by schroepf** [comment]
Hm... and it would still allow helprequests to remain in `ongoing` forever - and no one would ever work on it... would we need some kind of timeout in the backend at which they are automatically set back to `pending` (e.g. after 24 h or so)?
