### ISSUE TITLE
UI based phonenumber validation on registration is weak

### ISSUE THREAD

**Issue by KevinPeplinski** [NexdApp/nexd-ios#76]
UI Validation only checks for length of 3.

<img width="943" alt="Bildschirmfoto 2020-04-17 um 14 22 44" src="https://user-images.githubusercontent.com/10762938/79569114-557f5480-80b7-11ea-9b3e-32f876c0826a.png">

**Comment by fanick-ber** [comment]
We touched the validation already a bit in this issue: https://github.com/NexdApp/nexd-ios/issues/42

The backend uses the libphonenumber, which is also available for swift.

**Comment by KevinPeplinski** [comment]
I looked into libphonenumber for iOS. Can you provide some additional information about the implementation in the backend? I guess were using "DE" as defaultRegion?

**Comment by fanick-ber** [comment]
I am not passing in a region. It is used for validating without a region, therefore expecting the country code. I think this gives most flexibility. @andre-stefanov had some solution for Android in mind (maybe a country picker?)

**Comment by schroepf** [comment]
yes, we were thinking about having a "drop down" to chose the country code to have a consistent way of phone number formats (i.e. +49 vs. 0049)

**Comment by schroepf** [comment]
related to issue #42 (this also has some comments regarding phone number validation)
