### ISSUE TITLE
Create "light mode" for the text input fields on create help request screens

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-ios#95]
To improve readability we should implement a "light mode" for the text input fields and add similar validation rules as we did for the registration screens, as they are currently hard to read and not validated at all:

![Bild von iOS (3)](https://user-images.githubusercontent.com/2974425/79682028-30a5f100-821f-11ea-8214-41557cc5ccc4.png)

**Comment by KevinPeplinski** [comment]
What style is prefered for the borderLine, or do we keep the greyish? Its kinda hard for the eyes. 

![image1](https://user-images.githubusercontent.com/10762938/79750351-18160380-8311-11ea-8cfb-56d785d36381.png)

![image2](https://user-images.githubusercontent.com/10762938/79750370-1fd5a800-8311-11ea-9914-e230311b3156.png)

**Comment by schroepf** [comment]
@KevinPeplinski I prefer the white text and white border line for now... just make sure to define a custom color style for them in `Colors.xcassets` so we can easily change it later on when the designers come up with new designs in the future...

**Comment by KevinPeplinski** [comment]
Hey @schroepf, im sick :( cleared the assignment so someone else can pick this up. Once im healthy again I will pick up a new issue or this one again (if its still open by then)

**Comment by schroepf** [comment]
Alright! Thanks for letting us know! Get well, Soon!

**Comment by schroepf** [comment]
Regarding the design of the textfields I decided to use the same design as is used on the TranscribeInfoView (and convert the `RequestConfirmationViewController` to SwiftUI during that move):

![Simulator Screen Shot - iPhone 11 - 2020-04-22 at 22 49 36](https://user-images.githubusercontent.com/2974425/80199087-3d608580-8621-11ea-801c-a03623713188.png)
